# Generated by Django 2.2.5 on 2021-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210429_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='payload',
            field=models.IntegerField(default=0, verbose_name='payload'),
        ),
    ]
